### ISSUE TITLE
matrix.cpp:310: error: (-215) s >= 0 in function cv::setSize

### ISSUE THREAD

**Issue by ghost** [informramiz/opencv-face-recognition-python#7]
matrix.cpp:310: error: (-215) s >= 0 in function cv::setSize 
i am getting this error at:
-> face_recognizer.train(faces, np.array(labels))

why?

this is a labels np.array:

[0 0 0 1 2 2 2 3 3 3 3 4 4 4 5 5]

and this is a list of faces:

[array([ 36, 22, 244, 244]), array([ 20, 23, 249, 249]), array([ 32, 20, 245, 245]), array([ 39, 26, 239, 239]), array([ 19, 23, 248, 248]), array([ 28, 22, 235, 235]), array([ 28, 11, 243, 243]), array([ 39, 26, 238, 238]), array([ 27, 26, 243, 243]), array([ 21, 21, 257, 257]), array([ 35, 30, 245, 245]), array([ 33, 28, 246, 246]), array([ 24, 20, 257, 257]), array([ 32, 27, 250, 250]), array([ 35, 31, 232, 232]), array([ 35, 25, 236, 236])]

what is a problem?

**Comment by ghost** [comment]
it was my fault sorry

**Comment by dhruv-dj** [comment]
What was the error?

**Comment by ghost** [comment]
what was the issue, I am getting the same Error. 
The error i am getting is as follows-

error: (-215:Assertion failed) s >= 0 in function 'cv::setSize'
